### PR TITLE
Fix protos

### PR DESCRIPTION
**Pull request by morrowc**
I'm certain (almost certain) that there are some c and likely python changes required before this is safe/sane... but the current method to define these protos isn't really terrific :(

Since these are all parts of the same 'package', they ought to conform to the proper standards.

### CODE REVIEW

**Comment by morrowc** [comment]
fwiw, it looks like the nmsg package compiles with these changes included, so perhaps the proto usage was such that the changes aren't impactful? seems odd, but ... :) compiles! :)

**Comment by morrowc** [comment]
This seems to fix #69

**Comment by cmikk** [comment]
The enum changes here rename the associated enum types and values generated by protobuf-c. For example: 
```
NMSG__BASE__DNS_QRTYPE__UDP_QUERY_RESPONSE
```
becomes
```
NMSG__BASE__DNS_QR__DNS_QRTYPE__UDP_QUERY_RESPONSE
```
(note the insertion of the message type name after the BASE). This causes the supporting C code for the nmsg/base module to fail to compile without the corresponding renaming, and will do the same for any external C code which uses the protobuf-c representation of the message.

So, this is not a backward-compatible change and will require some code which uses nmsg to have the affected enum values renamed and recompiled. That said, this is a small renaming, akin to that required by the changes in PR #72

**Comment by morrowc** [comment]
I think my reply mail got lost in the github toaster:
<snip>
On Tue, 15 Oct 2019 14:01:55 -0700,
Chris Mikkelson <notifications@github.com> wrote:
> 
> [1 <text/plain; UTF-8 (7bit)>] The enum changes here rename the
> associated enum types and values generated by protobuf-c. For
> example:
> ``` NMSG__BASE__DNS_QRTYPE__UDP_QUERY_RESPONSE ``` becomes
> ``` NMSG__BASE__DNS_QR__DNS_QRTYPE__UDP_QUERY_RESPONSE ``` (note the
> insertion of the message type name after the BASE). This causes the
> supporting C code for the nmsg/base module to fail to compile
> without the corresponding renaming, and will do the same for any
> external C code which uses the protobuf-c representation of the
> message.
> 

Agreed that I thought this would cause problems (that's in the main /
OP), oddly that doesn't actually show up as a problem in your code's tests...
which I find 'odd'. :)

> So, this is not a backward-compatible change and will require some
> code which uses nmsg to have the affected enum values renamed and
> recompiled. That said, this is a small renaming, akin to that
> required by the changes in PR #72
>

agreed, but the base definition of the proto here is, actually, wrong.
Meaning, all of the proto files in this change set are part of,
ostensibly, a single package. That package has to be internally
consistent and right now it's not.

I'm happy to abandon this, or to work out some further bits to make it
happier.  I'd caution that I'm not a c-programmer by trade though :)

where would you like to see this go?

-chris
< end snip >

it seems like you agree it's "ok" to move forward, but that some other re-name actions are likely to be an outcome.

I'm curious as to why the tests seem to pass though? perhaps the proto parts aren't particularly well tested in the code?

**Comment by cmikk** [comment]
Regarding the tests, I am not sure how they passed on your system; the 'base' message module (required by the tests) did not compile on mine. Is it possible you were running tests against the unmodified message module somehow? Modifying the .proto files should have regenerated the .pb-c.[ch] files and caused the compilation to fail, so this seems odd to me.

I'm still figuring out the impact of the enum renaming in practice, i.e., the cost of the fix. As for the benefit side, I'm happy to advise on alternate workarounds to the problem.

**Comment by morrowc** [comment]
oh facepalm :( I did a pull and make, but didn't grab the branch with the current change in it :(

done now though...

morrowc@build:~/scripts/git/nmsg (origin/fix_protos)$ tests/nmsg.test  2>&1 | grep -v PASS
executing tests in directory tests/udp-checksum-tests
executing tests in directory tests/payload-crc32c-tests
executing tests in directory tests/nmsg-dnstap-tests
executing tests in directory tests/json-utf8-tests
executing tests in directory tests/string-tests
morrowc@build:~/scripts/git/nmsg (origin/fix_protos)$ 

I probably don't know how to make the proper tests run :(  they SEEM to be passing, again I'm totally sure I'm doin' it wrong :)

**Comment by morrowc** [comment]
omg... I suck at git :( 

ok, this time with feeling:
  CC       nmsg/base/nmsg_base_nmsg_msg9_base_la-nmsg_msg_base.lo
In file included from nmsg/base/nmsg_msg_base.c:53:0:
nmsg/base/ncap.c: In function ‘ncap_msg_load’:
nmsg/base/ncap.c:165:7: error: ‘NMSG__BASE__NCAP_TYPE__IPV4’ undeclared (first use in this function)
  case NMSG__BASE__NCAP_TYPE__IPV4:
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~


(and various other complaints in this same vein)

**Comment by morrowc** [comment]
Ok, added 2 more commits that clean up the bits/pieces of compile for the code, which (again, I think) take care of the tests?

```
morrowc@build:~/scripts/git/nmsg (fix_protos)$ tests/nmsg.test  2>&1 | grep -v PASS
executing tests in directory tests/udp-checksum-tests
executing tests in directory tests/payload-crc32c-tests
executing tests in directory tests/nmsg-dnstap-tests
executing tests in directory tests/json-utf8-tests
executing tests in directory tests/string-tests
morrowc@build:~/scripts/git/nmsg (fix_protos)$ 

```

**Comment by morrowc** [comment]
On Tue, 15 Oct 2019 14:01:55 -0700,
Chris Mikkelson <notifications@github.com> wrote:
> 
> [1 <text/plain; UTF-8 (7bit)>] The enum changes here rename the
> associated enum types and values generated by protobuf-c. For
> example:
> ``` NMSG__BASE__DNS_QRTYPE__UDP_QUERY_RESPONSE ``` becomes
> ``` NMSG__BASE__DNS_QR__DNS_QRTYPE__UDP_QUERY_RESPONSE ``` (note the
> insertion of the message type name after the BASE). This causes the
> supporting C code for the nmsg/base module to fail to compile
> without the corresponding renaming, and will do the same for any
> external C code which uses the protobuf-c representation of the
> message.
> 

Agreed that I thought this would cause problems (that's in the main /
OP), oddly that doesn't actually show up as a problem in your code's tests...
which I find 'odd'. :)

> So, this is not a backward-compatible change and will require some
> code which uses nmsg to have the affected enum values renamed and
> recompiled. That said, this is a small renaming, akin to that
> required by the changes in PR #72
>

agreed, but the base definition of the proto here is, actually, wrong.
Meaning, all of the proto files in this change set are part of,
ostensibly, a single package. That package has to be internally
consistent and right now it's not.

I'm happy to abandon this, or to work out some further bits to make it
happier.  I'd caution that I'm not a c-programmer by trade though :)

where would you like to see this go?

-chris

**Comment by morrowc** [comment]
Oh, now I see where my mails to github went.. #stupidmailtricks :( 

Anyway, I think the tests pass, there are commits which include fixing the new indirection to the protos.
How's this look to you now Chris?

**Comment by morrowc** [comment]
Still alive out there in github land?

**Comment by vixie** [comment]
here i am!

⁣Get BlueMail for Android ​

**Comment by morrowc** [comment]
hey awesome, how say you about this patch set? seem sane and submit-able? needs work? etc?

**Comment by cmikk** [comment]
Thanks, these new changes look good to me.

I have not finished reviewing the impact on other nmsg-using code, which we will need to understand and mitigate before merging this into master and releasing. It's possible that most code could be covered (i.e. would recompile cleanly with both the old and new versions of nmsg) with compatibility definitions in nmsg/base/defs.h, but I haven't surveyed all the code yet.

If all code is covered that way, this can be merged and released before the other non-backward-compatible changes  I alluded to above. Otherwise, I'd like to release both sets of changes requiring some user code modifications together.

Thanks for your patience on this and, as I said above, I'm happy to help with alternate workarounds if you need a faster released / packaged fix.

**Comment by morrowc** [comment]
> Thanks, these new changes look good to me.
> 

ok, cool.

> I have not finished reviewing the impact on other nmsg-using code, which we will need to understand and mitigate before merging this into master and releasing. It's possible that most code could be covered (i.e. would recompile cleanly with both the old and new versions of nmsg) with compatibility definitions in nmsg/base/defs.h, but I haven't surveyed all the code yet.
> 

ok, can I help with this as well? or is this code internal to FSI?

> If all code is covered that way, this can be merged and released before the other non-backward-compatible changes I alluded to above. Otherwise, I'd like to release both sets of changes requiring some user code modifications together.
> 

ok, cool.

> Thanks for your patience on this and, as I said above, I'm happy to help with alternate workarounds if you need a faster released / packaged fix.

I think for now I'm stumbling along with a copy of the protos haxored up so I can use them, and with a reference from ziegast to look at the go-nmsg codebase as well... so I'm probably ok for a week or 2, plus I have other $work things sucking up my used-to-be-free time used to look at the thing that got me to fixing this to start with :(

stupid jobs making work for me :( hehe.

**Comment by cmikk** [comment]
> ok, can I help with this as well? or is this code internal to FSI?

Most of the affected code is internal, and thank you for offering.

I was going to suggest go-nmsg as an alternative / workaround, but it turns out this protobuf refactor changes the type and value names there, too. Fortunately, go-nmsg has fewer users / uses and should be less impacted.

**Comment by cmikk** [comment]
I'm going to merge this work into a parallel branch on our side, and add compatibility definitions for the old names to `nmsg/compat.h` as we did when renaming the module from "isc" to "base". This should prevent most if not all conflicts in external code.

As far as I can tell, pynmsg will not be affected -- it does not use the protobuf-c generated code directly, but only through the nmsg accessors, whose operation appears unaffected by this change.

go-nmsg will be affected. I should be able to avoid an API revision there with similar compatibility definitions (type aliases, constants).

**Comment by morrowc** [comment]
awesome, thanks! glad to see this get easier to use :) (and more standard focused)

**Pull request merged**
